
// ReSharper disable InconsistentNaming

namespace Hai.ExpressionsEditor.Scripts.Editor.EditorUI
{
    public class EeLocaleDefaults
    {
        internal static string OfficialDocumentationUrlAsPrefix = "https://hai-vr.github.io/combo-gesture-expressions-av3/";
        internal static string EE_Documentation_URL = OfficialDocumentationUrlAsPrefix;
        internal static string EEA_No_animation_selected = "No animation selected.";
        internal static string EEA_Delete = "Delete";
        internal static string EEA_Reset_blendshapes_are_not_shown_above = "{0} reset blendshapes are not shown above.";
        internal static string EEA_Show_delete_reset_blendshapes = "Show/Delete reset blendshapes";
        internal static string EEA_Delete_zero_values = "Delete 0-values";
        internal static string EEA_Preview_animation_in_scene = "Preview animation in Scene";
        internal static string EEA_Scene_previews = "Scene previews";
        internal static string EEA_Select_animator_to_edit_animation = "Select animator to edit Animation";
        internal static string EEA_Generate_previews = "Generate previews";
        internal static string EEA_This_animation_has_additional_properties_not_shown_here = "This animation has additional properties not shown here:";
        internal static string EEA_Transform_related = "transform-related";
        internal static string EEA_Finger_posing_other_muscles_or_animator_related = "finger posing, other muscles, or Animator-related";
        internal static string EEA_Material_swaps = "material swaps";
        internal static string EEA_Shader_properties = "shader properties";
        internal static string EEA_Game_object_toggles = "game object toggles";
        internal static string EEA_Other_properties_not_cited_above = "other properties not cited above";
        internal static string EEA_This_animation_lasts_keyframes = "This animation lasts {0} keyframes.";
        internal static string EEA_This_animation_is_empty = "This animation is empty. This will cause the animation to last {0} keyframes.";
        internal static string EEA_All_of_the_keyframes_are_frame_zero = "All of the keyframes are located on frame 0. This will cause the animation to last {0} keyframes.";
        internal static string EEA_BlendshapeVaryingOverTimeWarning = "This animation contains blendshapes that are animated differently over time.\nThey cannot be edited in Expressions Editor. Preview may not be accurate.";
        internal static string EEA_AutogeneratedAnimationWarning = "This animation is likely auto-generated and may be overwritten at any time. You should probably not edit it.";
        internal static string EEA_VrcVisemeBlendshapeWarning = "This animation animates blendshapes that begin with vrc.v_, usually designed for Visemes.\nIf any animation contains those, the mouth may not animate properly.";
        internal static string EEA_BlinkBlendshapeWarning = "This animation animates a blendshape called Blink, usually selected to make the avatar blink automatically.\nIf any animation contains it, the avatar may not blink properly.\nMany avatar bases have blendshapes to close each eye separately; they should be used instead.";
        internal static string EEA_PreviewDummy = "Preview dummy";
        internal static string EEA_Automatically_setup_preview = "Automatically setup preview!";
        internal static string EEA_Camera = "Camera";
        internal static string EEP_Show_hotspots = "Show Hotspots (press SPACE key)";
        internal static string EEP_Other_tools = "Other tools";
        internal static string EEP_Fix_tooth_and_other_hidden_blendshapes = "Fix Tooth and other hidden blendshapes";
        internal static string EEP_Assign = "Assign";
        internal static string EEP_Forget = "Forget";
        internal static string EEP_Select = "Select";
        internal static string EEP_Generate_previews = "Generate previews";
        internal static string EEA_Rename = "Rename";
    }
}
