
// ReSharper disable InconsistentNaming

using System.Linq;
using System.Reflection;
using System.Text;
using Hai.ExpressionsEditor.Scripts.Editor.Internal;
using UnityEngine;

namespace Hai.ExpressionsEditor.Scripts.Editor.EditorUI
{
    public class EeLocale
    {
        internal static string CORE_Switch = "Switch language (English / 日本語)";
        internal static string CORE_Inaccuracy = "一部の翻訳は正確ではありません。ee.jp.jsonを編集することができます。";

        private static string EE_Documentation_URL => LocalizeOrElse("EE_Documentation_URL", EeLocaleDefaults.EE_Documentation_URL);
        //
        internal static string EEA_No_animation_selected => LocalizeOrElse("EEA_No_animation_selected", EeLocaleDefaults.EEA_No_animation_selected);
        internal static string EEA_Delete => LocalizeOrElse("EEA_Delete", EeLocaleDefaults.EEA_Delete);
        internal static string EEA_Reset_blendshapes_are_not_shown_above => LocalizeOrElse("EEA_Reset_blendshapes_are_not_shown_above", EeLocaleDefaults.EEA_Reset_blendshapes_are_not_shown_above);
        internal static string EEA_Show_delete_reset_blendshapes => LocalizeOrElse("EEA_Show_delete_reset_blendshapes", EeLocaleDefaults.EEA_Show_delete_reset_blendshapes);
        internal static string EEA_Delete_zero_values => LocalizeOrElse("EEA_Delete_zero_values", EeLocaleDefaults.EEA_Delete_zero_values);
        internal static string EEA_Preview_animation_in_scene => LocalizeOrElse("EEA_Preview_animation_in_scene", EeLocaleDefaults.EEA_Preview_animation_in_scene);
        internal static string EEA_Scene_previews => LocalizeOrElse("EEA_Scene_previews", EeLocaleDefaults.EEA_Scene_previews);
        internal static string EEA_Select_animator_to_edit_animation => LocalizeOrElse("EEA_Select_animator_to_edit_animation", EeLocaleDefaults.EEA_Select_animator_to_edit_animation);
        internal static string EEA_Generate_previews => LocalizeOrElse("EEA_Generate_previews", EeLocaleDefaults.EEA_Generate_previews);
        internal static string EEA_This_animation_has_additional_properties_not_shown_here => LocalizeOrElse("EEA_This_animation_has_additional_properties_not_shown_here", EeLocaleDefaults.EEA_This_animation_has_additional_properties_not_shown_here);
        internal static string EEA_Transform_related => LocalizeOrElse("EEA_Transform_related", EeLocaleDefaults.EEA_Transform_related);
        internal static string EEA_Finger_posing_other_muscles_or_animator_related => LocalizeOrElse("EEA_Finger_posing_other_muscles_or_animator_related", EeLocaleDefaults.EEA_Finger_posing_other_muscles_or_animator_related);
        internal static string EEA_Material_swaps => LocalizeOrElse("EEA_Material_swaps", EeLocaleDefaults.EEA_Material_swaps);
        internal static string EEA_Shader_properties => LocalizeOrElse("EEA_Shader_properties", EeLocaleDefaults.EEA_Shader_properties);
        internal static string EEA_Game_object_toggles => LocalizeOrElse("EEA_Game_object_toggles", EeLocaleDefaults.EEA_Game_object_toggles);
        internal static string EEA_Other_properties_not_cited_above => LocalizeOrElse("EEA_Other_properties_not_cited_above", EeLocaleDefaults.EEA_Other_properties_not_cited_above);
        internal static string EEA_This_animation_lasts_keyframes => LocalizeOrElse("EEA_This_animation_lasts_keyframes", EeLocaleDefaults.EEA_This_animation_lasts_keyframes);
        internal static string EEA_This_animation_is_empty => LocalizeOrElse("EEA_This_animation_is_empty", EeLocaleDefaults.EEA_This_animation_is_empty);
        internal static string EEA_All_of_the_keyframes_are_frame_zero => LocalizeOrElse("EEA_All_of_the_keyframes_are_frame_zero", EeLocaleDefaults.EEA_All_of_the_keyframes_are_frame_zero);
        internal static string EEA_BlendshapeVaryingOverTimeWarning => LocalizeOrElse("EEA_BlendshapeVaryingOverTimeWarning", EeLocaleDefaults.EEA_BlendshapeVaryingOverTimeWarning);
        internal static string EEA_AutogeneratedAnimationWarning => LocalizeOrElse("EEA_AutogeneratedAnimationWarning", EeLocaleDefaults.EEA_AutogeneratedAnimationWarning);
        internal static string EEA_VrcVisemeBlendshapeWarning => LocalizeOrElse("EEA_VrcVisemeBlendshapeWarning", EeLocaleDefaults.EEA_VrcVisemeBlendshapeWarning);
        internal static string EEA_BlinkBlendshapeWarning => LocalizeOrElse("EEA_BlinkBlendshapeWarning", EeLocaleDefaults.EEA_BlinkBlendshapeWarning);
        internal static string EEA_PreviewDummy => LocalizeOrElse("EEA_PreviewDummy", EeLocaleDefaults.EEA_PreviewDummy);
        internal static string EEA_Automatically_setup_preview => LocalizeOrElse("EEA_Automatically_setup_preview", EeLocaleDefaults.EEA_Automatically_setup_preview);
        internal static string EEA_Camera => LocalizeOrElse("EEA_Camera", EeLocaleDefaults.EEA_Camera);
        internal static string EEA_Rename => LocalizeOrElse("EEA_Rename", EeLocaleDefaults.EEA_Rename);
        internal static string EEP_Show_hotspots => LocalizeOrElse("EEP_Show_hotspots", EeLocaleDefaults.EEP_Show_hotspots);
        internal static string EEP_Other_tools => LocalizeOrElse("EEP_Other_tools", EeLocaleDefaults.EEP_Other_tools);
        internal static string EEP_Fix_tooth_and_other_hidden_blendshapes => LocalizeOrElse("EEP_Fix_tooth_and_other_hidden_blendshapes", EeLocaleDefaults.EEP_Fix_tooth_and_other_hidden_blendshapes);
        internal static string EEP_Assign => LocalizeOrElse("EEP_Assign", EeLocaleDefaults.EEP_Assign);
        internal static string EEP_Forget => LocalizeOrElse("EEP_Forget", EeLocaleDefaults.EEP_Forget);
        internal static string EEP_Select => LocalizeOrElse("EEP_Select", EeLocaleDefaults.EEP_Select);
        internal static string EEP_Generate_previews => LocalizeOrElse("EEP_Generate_previews", EeLocaleDefaults.EEP_Generate_previews);

        private static string LocalizeOrElse(string key, string defaultCultureLocalization)
        {
            return EeLocalization.LocalizeOrElse(key, defaultCultureLocalization);
        }

        public static string DocumentationUrl()
        {
            var localizedUrl = EE_Documentation_URL;
            return localizedUrl.StartsWith(EeLocaleDefaults.OfficialDocumentationUrlAsPrefix) ? localizedUrl : EeLocaleDefaults.EE_Documentation_URL;
        }

        public static string CompileDefaultLocaleJson()
        {
            var fields = typeof(EeLocaleDefaults).GetFields(BindingFlags.NonPublic | BindingFlags.Static);
            var jsonObject = new JSONObject();
            foreach (var field in fields.Where(info => info.Name.StartsWith("EE")))
            {
                jsonObject[field.Name] = new JSONString((string) field.GetValue(null));
            }

            var sb = new StringBuilder();
            jsonObject.WriteToStringBuilder(sb, 0, 0, JSONTextMode.Indent);
            return sb.ToString();
        }
    }
}
