using System;
using System.Collections.Generic;
using System.Linq;
using Hai.ComboGesture.Scripts.Components;
using UnityEditor;
using UnityEditor.Animations;
using UnityEngine;
using Object = UnityEngine.Object;

namespace Hai.ComboGesture.Scripts.Editor.Internal
{
    class AnimationNeutralizer
    {
        private readonly List<ActivityManifest> _originalActivityManifests;
        private readonly ConflictFxLayerMode _compilerConflictFxLayerMode;
        private readonly HashSet<CurveKey> _ignoreCurveKeys;
        private readonly Dictionary<CurveKey, float> _curveKeyToFallbackValue;
        private readonly string _datetimeForAssetPack;
        private readonly string _folderToCreateAssetIn;

        public AnimationNeutralizer(
            List<ActivityManifest> originalActivityManifests,
            ConflictFxLayerMode compilerConflictFxLayerMode,
            AnimationClip compilerIgnoreParamList,
            AnimationClip compilerFallbackParamList,
            string folderToCreateAssetIn)
        {
            _originalActivityManifests = originalActivityManifests;
            _compilerConflictFxLayerMode = compilerConflictFxLayerMode;
            _folderToCreateAssetIn = folderToCreateAssetIn;
            _ignoreCurveKeys = compilerIgnoreParamList == null ? new HashSet<CurveKey>() : ExtractAllCurvesOf(compilerIgnoreParamList);
            _curveKeyToFallbackValue = compilerFallbackParamList == null ? new Dictionary<CurveKey, float>() : ExtractFirstKeyframeValueOf(compilerFallbackParamList);
            _datetimeForAssetPack = DateTime.Now.ToString("yyyy'-'MM'-'dd'_'HHmmss");
        }

        private static HashSet<CurveKey> ExtractAllCurvesOf(AnimationClip clip)
        {
            return new HashSet<CurveKey>(AnimationUtility.GetCurveBindings(clip).Select(CurveKey.FromBinding));
        }

        private static Dictionary<CurveKey, float> ExtractFirstKeyframeValueOf(AnimationClip clip)
        {
            var curveKeyToFallbackValue = new Dictionary<CurveKey, float>();
            foreach (var editorCurveBinding in AnimationUtility.GetCurveBindings(clip))
            {
                var curve = AnimationUtility.GetEditorCurve(clip, editorCurveBinding);

                if (curve.keys.Length > 0)
                {
                    curveKeyToFallbackValue.Add(CurveKey.FromBinding(editorCurveBinding), curve.keys[0].value);
                }
            }

            return curveKeyToFallbackValue;
        }

        internal List<ActivityManifest> NeutralizeManifestAnimations()
        {
            var allAnimationClips = FindAllAnimationClips();
            var allApplicableCurveKeys = FindAllApplicableCurveKeys(allAnimationClips);

            var remapping = CreateAssetContainerWithNeutralizedAnimations(allAnimationClips, allApplicableCurveKeys);
            return _originalActivityManifests.Select(manifest => RemapManifest(manifest, remapping)).ToList();
        }

        private HashSet<AnimationClip> FindAllAnimationClips()
        {
            var allAnimationClips = _originalActivityManifests
                .SelectMany(manifest => manifest.Manifest.AnimationClips())
                .ToList();
            return new HashSet<AnimationClip>(allAnimationClips);
        }

        private static ActivityManifest RemapManifest(ActivityManifest manifest, Dictionary<AnimationClip, AnimationClip> remapping)
        {
            var remappedManifest = manifest.Manifest.NewFromRemappedAnimations(remapping);
            return new ActivityManifest(manifest.StageValue, remappedManifest, manifest.LayerOrdinal);
        }

        private Dictionary<AnimationClip, AnimationClip> CreateAssetContainerWithNeutralizedAnimations(HashSet<AnimationClip> allAnimationClips, HashSet<CurveKey> allApplicableCurveKeys)
        {
            var remapping = new Dictionary<AnimationClip, AnimationClip>();
            var assetContainer = new AnimatorController();

            AssetDatabase.CreateAsset(assetContainer, _folderToCreateAssetIn + "/GeneratedCGE__" + _datetimeForAssetPack + ".asset");

            foreach (var animationClip in allAnimationClips)
            {
                var neutralizedAnimation = CopyAndNeutralize(animationClip, allApplicableCurveKeys);
                AssetDatabase.AddObjectToAsset(neutralizedAnimation, assetContainer);

                remapping.Add(animationClip, neutralizedAnimation);
            }

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();

            return remapping;
        }

        private AnimationClip CopyAndNeutralize(AnimationClip animationClipToBePreserved, HashSet<CurveKey> allApplicableCurveKeys)
        {
            var copyOfAnimationClip = Object.Instantiate(animationClipToBePreserved);
            copyOfAnimationClip.name = "zAUTOGENERATED_" + animationClipToBePreserved.name + "_DO_NOT_EDIT";

            var bindings = AnimationUtility.GetCurveBindings(copyOfAnimationClip);
            var thisAnimationPaths = bindings
                .Select(CurveKey.FromBinding)
                .ToList();

            AddMissingCurveKeys(allApplicableCurveKeys, thisAnimationPaths, copyOfAnimationClip);
            RemoveExistingTransformsAndMuscleAnimations(thisAnimationPaths, copyOfAnimationClip);

            return copyOfAnimationClip;
        }

        private void RemoveExistingTransformsAndMuscleAnimations(List<CurveKey> thisAnimationPaths, AnimationClip copyOfAnimationClip)
        {
            if (_compilerConflictFxLayerMode != ConflictFxLayerMode.KeepBoth)
            {
                foreach (var curveKey in thisAnimationPaths)
                {
                    var isTransformOrMuscleCurve = curveKey.IsTransformOrMuscleCurve();
                    if (_compilerConflictFxLayerMode == ConflictFxLayerMode.KeepOnlyTransformsAndMuscles ? !isTransformOrMuscleCurve : isTransformOrMuscleCurve)
                    {
                        copyOfAnimationClip.SetCurve(curveKey.Path, curveKey.Type, curveKey.PropertyName, null);
                    }
                }
            }
        }

        private void AddMissingCurveKeys(HashSet<CurveKey> allApplicableCurveKeys, List<CurveKey> thisAnimationPaths, AnimationClip copyOfAnimationClip)
        {
            foreach (var curveKey in allApplicableCurveKeys)
            {
                if (!thisAnimationPaths.Contains(curveKey))
                {
                    var fallbackValue = _curveKeyToFallbackValue.ContainsKey(curveKey) ? _curveKeyToFallbackValue[curveKey] : 0;

                    Keyframe[] keyframes = {new Keyframe(0, fallbackValue), new Keyframe(1 / 60f, fallbackValue)};
                    var curve = new AnimationCurve(keyframes);
                    copyOfAnimationClip.SetCurve(curveKey.Path, curveKey.Type, curveKey.PropertyName, curve);
                }
            }
        }

        private HashSet<CurveKey> FindAllApplicableCurveKeys(HashSet<AnimationClip> allAnimationClips)
        {
            var curveKeys = allAnimationClips
                .SelectMany(AnimationUtility.GetCurveBindings)
                .Select(CurveKey.FromBinding)
                .Where(curveKey => !_ignoreCurveKeys.Contains(curveKey))
                .Where(curveKey =>
                {
                    switch (_compilerConflictFxLayerMode)
                    {
                        case ConflictFxLayerMode.RemoveTransformsAndMuscles: return !curveKey.IsTransformOrMuscleCurve();
                        case ConflictFxLayerMode.KeepBoth: return true;
                        case ConflictFxLayerMode.KeepOnlyTransformsAndMuscles: return curveKey.IsTransformOrMuscleCurve();
                        default:
                            throw new ArgumentOutOfRangeException();
                    }
                })
                .ToList();

            return new HashSet<CurveKey>(curveKeys);
        }
    }
}
